version: '3.9'
services:
  db:
    build:
      context: ./db
    environment:
      POSTGRES_USER: redshield
      POSTGRES_PASSWORD: redshield-is-awesome
      POSTGRES_DB: redshield_backend_development
    ports:
      - 5432:5432
  frontend:
    build:
      context: ./redshield-frontend
    ports:
      - 5172:3000
    depends_on:
      - db
  backend:
    build:
      context: ./redshield-backend
    environment:
      POSTGRES_USER: redshield
      POSTGRES_PASSWORD: redshield-is-awesome
      RAILS_MASTER_KEY: b59980a7398fc151c42059279af474ff
    ports:
      - 3000:3000
    depends_on:
      - db