version: '3.9'
services:
  db:
    container_name: db
    build:
      context: ./db
      target: db
    environment:
      POSTGRES_USER: redshield
      POSTGRES_PASSWORD: redshield-is-awesome
      POSTGRES_DB: redshield_backend_development
    ports:
      - 5432:5432
  # frontend:
  # backend:
